### ISSUE TITLE
Current develop does not work on 2.1.x

### ISSUE THREAD

**Issue by josegonzalez** [AD7six/cakephp-completion#3]
Works fine on 2.2.x. It appears to do it backwards due to internal api changes in 2.2.x:

![http://cl.ly/image/3H0x1B070U2X](http://f.cl.ly/items/3O0d293J2A0I1j0F0N0H/Screen%20Shot%202012-10-07%20at%206.22.24%20PM.png)

**Comment by AD7six** [comment]
Closing as "really? well I'll be."

Not worth fixing if it's still a problem though.
